on:
  workflow_dispatch:

name: build_and_upload_ctpl

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.9.18
          update-environment: true

      - name: Build and Upload
        env:
          PASS: ${{ secrets.PASS }}
        run: |
          mkdir script && cd script
          pip install lxml requests ddddocr -i https://pypi.org/simple --quiet
          curl -o HiddenPrints.py https://file.mirror.ct8.pl/dufs/public/edgetunnel-yxip/HiddenPrints.py
          echo -n ${{ secrets.SCRIPT_CTPL }} | base64 --decode > main.py
          python main.py
