on:
  workflow_dispatch:

name: build_and_upload_ctpl

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: sigoden/dufs

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: "x86_64-unknown-freebsd"
          override: true
