on:
  workflow_dispatch:

name: build_and_upload_PGPClipper

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: Mnkai/PGPClipper

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew assemble

      - name: Upload Binaries
        uses: actions/upload-artifact@v4.3.0
        with:
          name: PGPClipper_build
          path: app/build/outputs/apk/release/*.apk
          retention-days: 1
          compression-level: 0
          overwrite: true
